/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RenderWindow.java
 *
 * Created on 09/12/2010, 23:44:11
 */

package AZBIrenderer;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author user
 */
public class RenderWindow extends javax.swing.JFrame {

    /** Creates new form RenderWindow */
    public RenderWindow() {
        initComponents();
        this.setSize(400, 300);
        TextEditorWindow.setSize(200, 200);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextEditorWindow = new javax.swing.JDialog();
        TextToolbar = new javax.swing.JToolBar();
        TextOpenButton = new javax.swing.JButton();
        TextScroll = new javax.swing.JScrollPane();
        TextPane = new javax.swing.JTextPane();
        ImageToolbar = new javax.swing.JToolBar();
        RenderButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        ImageScroll = new javax.swing.JScrollPane();
        ImageView = new javax.swing.JLabel();

        TextEditorWindow.setTitle("Scene Text Editor");

        TextToolbar.setFloatable(false);
        TextToolbar.setRollover(true);

        TextOpenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AZBIrenderer/images/tango-open.png"))); // NOI18N
        TextOpenButton.setText("Open...");
        TextOpenButton.setFocusable(false);
        TextOpenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TextOpenButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TextToolbar.add(TextOpenButton);

        TextEditorWindow.getContentPane().add(TextToolbar, java.awt.BorderLayout.PAGE_START);

        TextPane.setText("scene:\nbackground-col=0.5 0.5 1\nambient-light=1 1 1\n\ncamera:\neye = -1 1.7 1\nlook-at = 0 0 0\nscreen-dist = 1\nup-direction = 0 1 0\n\nrectangle:\np0=-2 0 -2\np1=-2 0 2\np2=2 0 -2\n\nsphere:\ncenter = 0 0.5 0\nradius = 0.5\nmtl-diffuse=0.98 0.48 0.4\n\nsphere:\ncenter= 0 1 0.3\nradius=0.1\n\nlight-point:\npos= 0 4 -2\ncolor = 0.1 0.1 0.4\n\nlight-directed:\ndirection=0 -1 -1\ncolor= 0.8 0.8 0.8\n");
        TextScroll.setViewportView(TextPane);

        TextEditorWindow.getContentPane().add(TextScroll, java.awt.BorderLayout.LINE_END);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ImageToolbar.setFloatable(false);
        ImageToolbar.setRollover(true);

        RenderButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\University\\Tel-Aviv-Computer-Science\\Courses\\Computer Graphics\\RayTracer\\Jazbi\\src\\AZBIrenderer\\images\\tango-execute.png")); // NOI18N
        RenderButton.setText("Start Render!");
        RenderButton.setFocusable(false);
        RenderButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RenderButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RenderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenderButtonActionPerformed(evt);
            }
        });
        ImageToolbar.add(RenderButton);

        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AZBIrenderer/images/tango-save.png"))); // NOI18N
        SaveButton.setText("Save as PNG");
        SaveButton.setFocusable(false);
        SaveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveButton.setPreferredSize(new java.awt.Dimension(31, 41));
        SaveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ImageToolbar.add(SaveButton);

        EditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AZBIrenderer/images/tango-edit.png"))); // NOI18N
        EditButton.setText("Edit Scene...");
        EditButton.setFocusable(false);
        EditButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        ImageToolbar.add(EditButton);

        getContentPane().add(ImageToolbar, java.awt.BorderLayout.PAGE_START);

        ImageScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        ImageScroll.setMinimumSize(new java.awt.Dimension(50, 50));

        ImageView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageView.setText("Render will be here!");
        ImageView.setIconTextGap(0);
        ImageScroll.setViewportView(ImageView);

        getContentPane().add(ImageScroll, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RenderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenderButtonActionPerformed
        Render r = new Render(TextPane.getText());
        r.render(ImageScroll.getWidth(), ImageScroll.getHeight());
        ImageView.setIcon(new ImageIcon(r.render));
        ImageView.setText("");
    }//GEN-LAST:event_RenderButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        TextEditorWindow.setVisible(true);
        TextEditorWindow.requestFocus();
    }//GEN-LAST:event_EditButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) { }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RenderWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButton;
    private javax.swing.JScrollPane ImageScroll;
    private javax.swing.JToolBar ImageToolbar;
    private javax.swing.JLabel ImageView;
    private javax.swing.JButton RenderButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JDialog TextEditorWindow;
    private javax.swing.JButton TextOpenButton;
    private javax.swing.JTextPane TextPane;
    private javax.swing.JScrollPane TextScroll;
    private javax.swing.JToolBar TextToolbar;
    // End of variables declaration//GEN-END:variables

}
